@startuml
class Solution46 {
    +main()
    +Map parseAndCount(String)
    +List makeCountArr(Map)
}

class InputOutput {
    +String readFromFile()
    -outputToScreen(Map, List)
}

Solution46 o-- InputOutput
@enduml